ktor:
    application:
        modules:
            - top.hhs.xgn.ApplicationKt.module
    deployment:
        port: 8080

    development: true

model:
    host: "114.212.10.249"
    port: "8501"

token:
    admin: "admin"

prometheus:
    port: 8081