ktor:
    application:
        modules:
            - top.hhs.xgn.ApplicationKt.module
    deployment:
        port: 8080

    development: false

model:
    host: "localhost"
    port: "8501"

token:
    admin: "admin"
prometheus:
    port: 8081