ktor:
    application:
        modules:
            - top.hhs.xgn.ApplicationKt.module
    deployment:
        port: 8080

    development: true

model:
    host: "116.62.110.110"
    port: "8501"

token:
    admin: "admin"

prometheus:
    port: 8081